name: GW Security Checks
on:
  push:
    branches: 
      - master

jobs:
  build:
    name: security check
    runs-on: ubuntu-18.04
    steps:
      
      # - name: Create Security Checks directory
      #   run: |
      #     sudo mkdir security_checks

      - name: Checkout code 
        uses: actions/checkout@v2

      - name: Checkout Security Scripts
        uses: actions/checkout@v2
        with: 
          repository: virajut/security_checks
          token: ${{ secrets.MY_PAT }}
          path: security_checks

      - name: Install script dependencies
        run: |
          pwd
          ls -alt
          cd security_checks
          ls -alt
          sudo apt-get install gcc libpq-dev -y
          sudo apt-get install python-dev  python-pip -y
          sudo apt-get install python3-dev python3-pip python3-venv python3-wheel -y
          pip3 install wheel
          pip3 install setuptools
          pip3 install -r requirements.txt
        
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Install trivy
        run: |
          sudo apt-get install wget apt-transport-https gnupg lsb-release
          wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
          echo deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main | sudo tee -a /etc/apt/sources.list.d/trivy.list
          sudo apt-get update
          sudo apt-get install trivy -y
        
      - name: Run the security check script
        run: |
          export SLACK_API_TOKEN=${{ secrets.SLACK_API_TOKEN }}
          python3 ./security_checks/security_checks.py
